name: Build ALL
on:
  workflow_dispatch:
jobs:
  build-mac:
    runs-on: macos-10.15
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: 'Build Mobile SDK'
      run: bash ./tools/build-mac.sh
  build-windows:
    runs-on: windows-2019
    needs: build-mac
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: 'Build Windows SDK'
      run: bash ./tools/build-win.sh
