name: Release Open
on:
  workflow_dispatch:
jobs:
  build-mac:
    runs-on: macos-10.15
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: 'Release Open'
      run: bash ./tools/gamelib.sh release-open --updateVersions=./VERSIONS-update
