name: Manual Trigger
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'command'
        required: true
        default: 'version'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - if: ${{ github.event.inputs.command == 'release-open' }}
      run: echo "execute release open"
    - if: ${{ github.event.inputs.command == 'release-close' }}
      run: echo "execute release close"
    - if: ${{ github.event.inputs.command == 'version' }}
      run: echo "1.0.0"
    - name: 'bash script file test'
      run: bash ./tools/test.sh
