name: Manual Trigger
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'command'
        required: true
        default: 'version'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "command=${{ github.event.inputs.command }}"
